fix: debug

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -25,7 +25,7 @@ jobs:
   terraform-validation:
     runs-on: ubuntu-24.04
     env:
-      TF_LOG_LEVEL: DEBUG
+      TF_LOG: DEBUG
     needs: find-modules
     if: ${{ fromJson(needs.find-modules.outputs.modules)[0] != null }}
     strategy:
@@ -137,3 +137,12 @@ jobs:
         if: always()
         run: |
           rm -f terraform/modules/${{ matrix.module }}/terraform.tfvars
+  results:
+    name: PR Results
+    needs: terraform-validation
+    if: always()
+    runs-on: ubuntu-24.04
+    steps:
+      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
+        run: echo "At least one job has failed." && exit 1
+      - run: echo "Success!"
